export const HERO_FARMING_CONFIG = {
    // === Type 1: 节奏/GANK型 ===
    "LeeSin": { tier: 0, farming_stars: 2, standard_stars: 5, reason_farming: "野核模式：效率低，浪费前期强势期", reason_standard: "标准模式：T0级前期节奏，野区单挑与Gank极强" },
    "XinZhao": { tier: 0, farming_stars: 2, standard_stars: 5, reason_farming: "野核模式：缺乏AOE速刷手段，拖后期乏力", reason_standard: "标准模式：捅脸单挑强，适合主动入侵找节奏" },
    "Viego": { tier: 0, farming_stars: 3, standard_stars: 5, reason_farming: "野核模式：虽有收割能力，但纯刷容易丢失节奏", reason_standard: "标准模式：捡魂收割机制，团战上限极高" },
    "Vi": { tier: 0, farming_stars: 3, standard_stars: 5, reason_farming: "野核模式：有W刷野尚可，但核心是锁头抓人", reason_standard: "标准模式：Q闪开团，大招必中，专治花里胡哨" },
    "Wukong": { tier: 0, farming_stars: 2, standard_stars: 5, reason_farming: "野核模式：除了神分那一波，刷野并不快", reason_standard: "标准模式：隐身切入，大招两段击飞，最强团控战士" },
    "Olaf": { tier: 0, farming_stars: 4, standard_stars: 5, reason_farming: "野核模式：虽然丢斧子刷得快，但更适合砍人", reason_standard: "标准模式：诸神黄昏免控，疯狗一样冲脸C位" },
    "Warwick": { tier: 0, farming_stars: 2, standard_stars: 5, reason_farming: "野核模式：没有提亚马特之前刷野很慢", reason_standard: "标准模式：鲜血追猎，全图加速，低分段战神" },
    "Briar": { tier: 0, farming_stars: 3, standard_stars: 5, reason_farming: "野核模式：虽然有回复，但失控机制容易送", reason_standard: "标准模式：全图大招支援，疯狗吸血，残局战神" },
    "Pantheon": { tier: 0, farming_stars: 2, standard_stars: 5, reason_farming: "野核模式：刷野极慢，后期乏力", reason_standard: "标准模式：W稳定点控，大招半图支援跳后排" },
    "JarvanIV": { tier: 0, farming_stars: 1, standard_stars: 5, reason_farming: "野核模式：刷野伤且慢，无法发挥EQ二连优势", reason_standard: "标准模式：绝食流代表，二级抓下/三级越塔" },
    "Nunu": { tier: 0, farming_stars: 3, standard_stars: 5, reason_farming: "野核模式：吃野怪快但CARRY能力差", reason_standard: "标准模式：推球跑图，控龙与抓人效率极高" },
    "Twitch": { tier: 0, farming_stars: 1, standard_stars: 5, reason_farming: "野核模式：身板脆刷野慢，不抓人就废了", reason_standard: "标准模式：隐身一级抓人，通过恶心线上滚雪球" },
    "Sylas": { tier: 0, farming_stars: 2, standard_stars: 5, reason_farming: "野核模式：前期刷野像坐牢，必须去线上'借'钱", reason_standard: "标准模式：偷取关键大招（如石头人/阿木木）逆天改命" },
    "Poppy": { tier: 0, farming_stars: 2, standard_stars: 5, reason_farming: "野核模式：Q有百分比但手短，更需要跑图", reason_standard: "标准模式：W防突进神技，E壁咚，R锤飞关键前排" },
    "Evelynn": { tier: 0, farming_stars: 4, standard_stars: 5, reason_farming: "野核模式：6级前需速刷，但核心是杀人叠层数", reason_standard: "标准模式：隐身抓人，高爆发秒C位" },
    "Talon": { tier: 0, farming_stars: 3, standard_stars: 5, reason_farming: "野核模式：翻墙是为了跑图杀人，不是为了刷F6", reason_standard: "标准模式：全图游走，利用高机动性抓崩三路" },
    "Shaco": { tier: 0, farming_stars: 1, standard_stars: 5, reason_farming: "野核模式：纯刷是最差的玩法，必须搞事", reason_standard: "标准模式：绝食骚扰，通过折磨对手心态获胜" },
    "KhaZix": { tier: 0, farming_stars: 3, standard_stars: 5, reason_farming: "野核模式：孤立无援适合野区单挑，但需要人头", reason_standard: "标准模式：进化技能，蜻蜓点水，收割残局" },
    "Rengar": { tier: 0, farming_stars: 3, standard_stars: 5, reason_farming: "野核模式：草丛跳跃刷野快，但大招是核心", reason_standard: "标准模式：落地秒杀，寻找脆皮提款" },
    "Qiyana": { tier: 0, farming_stars: 2, standard_stars: 5, reason_farming: "野核模式：刷野伤，极其依赖装备优势", reason_standard: "标准模式：水元素禁锢，大招推墙奇迹团" },
    "Nocturne": { tier: 0, farming_stars: 4, standard_stars: 5, reason_farming: "野核模式：速6虽然重要，但本质是关灯抓单", reason_standard: "标准模式：关灯让对面丧失视野，定点秒杀C位" },
    "Elise": { tier: 0, farming_stars: 1, standard_stars: 5, reason_farming: "野核模式：刷野最慢梯队，后期超级兵", reason_standard: "标准模式：越塔女皇，必须在20分钟前结束比赛" },
    "RekSai": { tier: 0, farming_stars: 2, standard_stars: 5, reason_farming: "野核模式：虽然有AOE，但机制决定必须进攻", reason_standard: "标准模式：隧道挖掘，听声辨位，前期压制力强" },
    "Gragas": { tier: 0, farming_stars: 2, standard_stars: 5, reason_farming: "野核模式：AP流可刷，但肉装流必须做事", reason_standard: "标准模式：E闪开团，几何桶分割战场" },

    // === Type 2: 野核/发育型 ===
    "Lillia": { tier: 5, farming_stars: 5, standard_stars: 3, reason_farming: "野核模式：移速拉扯，多刷一组野就多一分胜算", reason_standard: "标准模式：缺乏硬控，Gank依赖E技能命中" },
    "Karthus": { tier: 5, farming_stars: 5, standard_stars: 2, reason_farming: "野核模式：全图支援，利用刷野拉开等级差", reason_standard: "标准模式：Gank能力极弱，只能反蹲或捡漏" },
    "Taliyah": { tier: 5, farming_stars: 5, standard_stars: 3, reason_farming: "野核模式：AOE足，刷野快，后期控场法师", reason_standard: "标准模式：虽有大招支援，但发育优先" },
    "Brand": { tier: 5, farming_stars: 5, standard_stars: 2, reason_farming: "野核模式：被动百分比伤害，刷野速度极快", reason_standard: "标准模式：腿短无位移，容易被抓" },
    "Zyra": { tier: 5, farming_stars: 5, standard_stars: 2, reason_farming: "野核模式：植物抗怪无伤刷野，经济转化率高", reason_standard: "标准模式：控制不稳定，身板脆" },
    "Fiddlesticks": { tier: 5, farming_stars: 5, standard_stars: 4, reason_farming: "野核模式：多野怪同时拉刷，速6是唯一真理", reason_standard: "标准模式：视野排空后的跳大是恐怖游戏" },
    "Morgana": { tier: 5, farming_stars: 5, standard_stars: 2, reason_farming: "野核模式：W刷野不仅快还能吸血，无伤打野", reason_standard: "标准模式：只能摸奖Q，容易被反烂" },
    "Ekko": { tier: 4, farming_stars: 4, standard_stars: 4, reason_farming: "野核模式：三环刷野快，大招容错，吃装备", reason_standard: "标准模式：W立场预判，越塔强杀" },
    "Diana": { tier: 4, farming_stars: 5, standard_stars: 3, reason_farming: "野核模式：被动攻速，速6质变，纳什之牙", reason_standard: "标准模式：依赖Q技能突进，6级前较弱" },
    "Nidalee": { tier: 4, farming_stars: 5, standard_stars: 4, reason_farming: "野核模式：刷野天花板，等级压制是核心", reason_standard: "标准模式：标枪摸奖，人形态加血，操作难度高" },
    "Graves": { tier: 4, farming_stars: 5, standard_stars: 4, reason_farming: "野核模式：纯爷们反野，把对面野区当自己家", reason_standard: "标准模式：烟雾弹Gank，配合线上推塔" },
    "Kindred": { tier: 4, farming_stars: 5, standard_stars: 3, reason_farming: "野核模式：印记成长需求，必须入侵吞噬野怪", reason_standard: "标准模式：依赖队友保护，印记刷新看运气" },
    "MasterYi": { tier: 4, farming_stars: 5, standard_stars: 2, reason_farming: "野核模式：吞噬野区，后期砍瓜切菜", reason_standard: "标准模式：前期无控，只能收割残局" },
    "Belveth": { tier: 4, farming_stars: 5, standard_stars: 3, reason_farming: "野核模式：无限攻速成长，必须拿虚空鱼", reason_standard: "标准模式：Q技能多段位移，E技能减伤" },
    "Hecarim": { tier: 4, farming_stars: 5, standard_stars: 3, reason_farming: "野核模式：Q技能AOE，贪婪刷野叠装备", reason_standard: "标准模式：疾跑一开，谁也不爱，主要靠冲阵" },
    "Jax": { tier: 4, farming_stars: 4, standard_stars: 3, reason_farming: "野核模式：刷野速度中等但成长性极高", reason_standard: "标准模式：反击风暴晕人，后期单带无解" },
    "Kayn": { tier: 3, farming_stars: 4, standard_stars: 4, reason_farming: "野核模式：蓝凯秒人，红凯回血，都需要装备", reason_standard: "标准模式：穿墙游走，蹭能量变身" },
    "Jayce": { tier: 4, farming_stars: 4, standard_stars: 3, reason_farming: "野核模式：锤形态AOE刷野，需要大量经济支撑Poke", reason_standard: "标准模式：加强炮消耗，如无经济压制则作用有限" },
    "Teemo": { tier: 4, farming_stars: 4, standard_stars: 2, reason_farming: "野核模式：6级后蘑菇阵控图，恶心对面野区", reason_standard: "标准模式：正面团战弱，容易被针对" },
    "Shyvana": { tier: 4, farming_stars: 5, standard_stars: 2, reason_farming: "野核模式：速6变龙，控龙属性加成", reason_standard: "标准模式：没大招超级兵，只能反蹲" },
    "DrMundo": { tier: 4, farming_stars: 5, standard_stars: 3, reason_farming: "野核模式：E技能拍死野怪，经济转化为坦度", reason_standard: "标准模式：去哪全凭心情，吸收成吨伤害" },
    "Udyr": { tier: 3, farming_stars: 4, standard_stars: 4, reason_farming: "野核模式：觉醒R刷野极快，跑图流", reason_standard: "标准模式：E技能加速晕人，形态切换灵活" },

    // === Type 3: 工具人/功能型 ===
    "Sejuani": { tier: 0, farming_stars: 2, standard_stars: 5, reason_farming: "野核模式：肉装为主，刷野慢，CARRY难", reason_standard: "标准模式：被动抗性，大招开团，配合近战队友" },
    "Rammus": { tier: 0, farming_stars: 1, standard_stars: 5, reason_farming: "野核模式：被法师折磨，刷野效率低", reason_standard: "标准模式：物理克星，Q加速抓人，嘲讽必杀" },
    "Amumu": { tier: 0, farming_stars: 2, standard_stars: 5, reason_farming: "野核模式：虽然E技能刷野快，但容易被反", reason_standard: "标准模式：QW粘人，R大团控，也是个好工具人" },
    "Zac": { tier: 0, farming_stars: 2, standard_stars: 5, reason_farming: "野核模式：捡碎片回血，但单挑能力弱", reason_standard: "标准模式：超远E开团，分割战场，多重控制" },
    "Maokai": { tier: 0, farming_stars: 2, standard_stars: 5, reason_farming: "野核模式：树苗探视野，自身伤害不足", reason_standard: "标准模式：W稳定点控，R大范围封路" },
    "Ivern": { tier: 0, farming_stars: 1, standard_stars: 5, reason_farming: "野核模式：我是辅助，为什么要让我C？", reason_standard: "标准模式：种草护盾，召唤小菊，纯辅助玩法" },
    "Skarner": { tier: 0, farming_stars: 2, standard_stars: 5, reason_farming: "野核模式：重做后偏肉坦控制", reason_standard: "标准模式：E技能穿墙，R压制拉人" },
    "Volibear": { tier: 0, farming_stars: 3, standard_stars: 5, reason_farming: "野核模式：被动闪电链刷野不错，但手短", reason_standard: "标准模式：大招屏蔽防御塔，越塔神技" },
    "Malphite": { tier: 0, farming_stars: 2, standard_stars: 5, reason_farming: "野核模式：前期缺蓝刷得慢，除了大招没别的", reason_standard: "标准模式：只要大招撞得好，0-5也能赢团战" },
    "Shen": { tier: 0, farming_stars: 1, standard_stars: 5, reason_farming: "野核模式：清野巨慢，甚至需要提亚马特", reason_standard: "标准模式：大招全图保人，E闪嘲讽开团" },
    "Gwen": { tier: 3, farming_stars: 4, standard_stars: 3, reason_farming: "野核模式：真实伤害，W规避技能，后期大核", reason_standard: "标准模式：留人能力差，依赖疾跑" },
    "Aatrox": { tier: 3, farming_stars: 3, standard_stars: 4, reason_farming: "野核模式：吸血续航，野区单挑强", reason_standard: "标准模式：多段击飞，团战天神下凡" }
};